apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookmarky-stage
resources:
  - ../../base
  - network.yaml
  # - secret.yaml
images:
  - name: harbor.squid-ink.us/politeauthority/bookmarky
    newTag: 0.0.1.1
