name: Push Main

on:
  push:
    branches: ["main", "cicd"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # new-stage:
  #   uses: ./.github/workflows/generic-task.yaml
  #   secrets: inherit
  #   permissions:
  #     pull-requests: read
  #     contents: read
  #   with:
  #     task: "ci-new-stage"

  validate:
    uses: ./.github/workflows/validate.yaml
    needs: [new-stage]
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-api:
    needs: [validate]
    uses: ./.github/workflows/build-container-api.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "prod"
      build-target: "base"

  # deploy:
  #   runs-on: self-hosted
  #   needs: [build-api]
  #   container:
  #     image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
  #     credentials:
  #       username: ${{ vars.HARBOR_USER }}
  #       password: ${{ secrets.HARBOR_PASSWORD }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.PAT }}
  #     - name: Deploy Main
  #       run: |
  #         mkdir ~/.kube
  #         echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
  #         export KUBECONFIG=~/.kube/config.yaml
  #         chmod 600 ~/.kube/config.yaml
  #         task stage-deploy
# End File: politeauthority/bookmarky/.github/workflows/push-main.yaml
