name: Staging

on:
  pull_request:
    branches: ["stage"]
  push:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # validate-pep8:
  #   runs-on: self-hosted
  #   container:
  #     image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
  #     credentials:
  #       username: ${{ vars.HARBOR_USER }}
  #       password: ${{ secrets.HARBOR_PASSWORD }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.PAT }}
  #     - name: Validate Pep8
  #       run: |
  #         pipx install flake8
  #         python3.11 -m flake8 --config=src/flake8 src

  validate:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Validate K8s Manifests
        run: |
          kustomize build kubernetes-manifests/base >> /dev/null
          kustomize build kubernetes-manifests/envs/prod >> /dev/null
          kustomize build kubernetes-manifests/envs/stage >> /dev/null
          kustomize build kubernetes-manifests/envs/dev >> /dev/null
      # - name: Install Dependancies
      #   run: |
      #     python3.11 -m pip install .

  build-api:
    needs: [unit-tests]
    uses: ./.github/workflows/build-container-api.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy:
    runs-on: self-hosted
    needs: [build]
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Deploy Staging
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config.yaml
          task stage-deploy

# End File: politeauthority/bookmarky/.github/workflows/staging.yaml
